// <auto-generated />
using System;
using Kbs.IdoWeb.Data.Mapping;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Kbs.IdoWeb.Data.Migrations.Mapping
{
    [DbContext(typeof(MappingContext))]
    partial class MappingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Kbs.IdoWeb.Data.Mapping.Tk25", b =>
                {
                    b.Property<int>("Tk25Id");

                    b.Property<decimal?>("GkCenterLat")
                        .HasColumnType("numeric(18,15)");

                    b.Property<decimal?>("GkCenterLong")
                        .HasColumnType("numeric(18,15)");

                    b.Property<int?>("GkEpsg");

                    b.Property<string>("Title")
                        .HasMaxLength(200);

                    b.Property<int?>("Tk25IdV2");

                    b.Property<int>("TkNr");

                    b.Property<int?>("TkQuadrant");

                    b.Property<decimal?>("Wgs84CenterLat")
                        .HasColumnType("numeric(18,15)");

                    b.Property<decimal?>("Wgs84CenterLong")
                        .HasColumnType("numeric(18,15)");

                    b.HasKey("Tk25Id");

                    b.ToTable("Tk25","Map");
                });
#pragma warning restore 612, 618
        }
    }
}
